prefix='/home/lcims/omc/omc-alarm-3.0'
sh{
    LANG='zh_CN.utf8';
    target='omc_alarm';
}
smtp{
    host='smtp.sina.cn';
    username='omcalarm@sina.cn';
    password='omc_admin1';
}
smsshellpath='/data/omc/alarm/sh/sms';
alarm_min_num=-1
out_db_exist=false
environments {
    dev{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_nmcu?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        dbOut{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_nmcu?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
		upload{
             serverIp='10.21.20.114';
             serverPort='22';
             protocol='sftp';
             loginName='lcims';
             password='ndmxsfzsssey';
             localDir='/home/lcims/omc/upload';
             uploadDir='/lcims/omc/upload';
             metric_identitys='memory_use_rate,cpu_use_rate,disk_busy_rate';
        }
        JAVA_HOME='/home/lcims/app/jdk8';
        log.home='/home/lcims/omc/omc-alarm-3.0/logs';
        sendReport=true;
        province=dev;
    }
	demo{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_demo?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/home/lcims/app/jdk8';
        log.home='/home/lcims/omcdemo/omc-alarm-3.0/logs';
        sendReport=true;
        province=demo;
    }
	nmcu{
	    prefix='/export/home/omc/omc-alarm-3.0'
        db{ 
			driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@110.19.17.31:1521:aiomc';
            username='omc';
            password='omc_nmlt';
			initSize='10';
            maxActive='50';
            name='oracle';
        }
		sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
		smtp{
            host='smtp.126.com';
            username='nmgtangyh@126.com';
            password='tangyh521';
        }
        JAVA_HOME='/export/home/omc/app/jdk1.8.0_181';
        log.home='/export/home/omc/omc-alarm-3.0/logs';
        sendReport=true;
        province='nmcu';
    }
	
	 sicu{
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@218.26.146.13:1521:ORA11G';
            username='aimnt';
            password='Aisicuomc123#';
            initSize='10';
            maxActive='50';
            name='oracle';
        }
		smtp{
		    host='smtp.163.com';
		    username='obsmnt@163.com';
		    password='omc2018';
		}
		  sh{
            LANG='zh_CN.UTF-8';
            target='omc-alarm';
        }
        prefix='/home/omc/omc-alarm';
		JAVA_HOME='/home/omc/jdk8';
        log.home='/home/omc/omc-alarm/logs'
		sendReport='true'
		province=sicu;
      
   }
   
   xjcu{
		prefix='/home/omc/omc-alarm-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://10.7.15.38:3306/omc_xjcu?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8';
            username='omc';
            password='Omc@1234';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
		smtp{
            
        }
        JAVA_HOME='/home/omc/app/jdk1.8';
        log.home='/home/omc/omc-alarm-3.0/logs';
        sendReport=false;
        province=xjcu;
    }
	 nmct{
		prefix='/omc/omc-alarm-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://192.168.100.80:3306/omc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8';
            username='omc';
            password='nmobs%3A';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
		smtp{
            
        }
        JAVA_HOME='/home/jdk1.8.0_181';
        log.home='/omc/omc-alarm-3.0/logs';
        sendReport=false;
        province='nmct';
    }
	gscm{
		prefix='/home/omc/omc-alarm-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.8.103:3306/gsomc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8';
            username='gsomc';
            password='GSomc@0105';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
		smtp{
            
        }
		upload{
             serverIp='192.168.6.44';
			 serverIpSB='10.238.67.46';
             serverPort='21';
             protocol='ftp';
			 protocolSB='ftp';
             loginName='KXshuju';
			 loginNameSB='gcp';
             password='KX22019QAZx';
             passwordSB='WGjk-113';
             localDir='/home/omc/ftpdatas/kd_band';
             uploadDir='/home/KXshuju/month';
			 uploadDirSb='/opt/Gcp/ZJXN'
			 metric_identitysSb='read_wrtn_speed,multi_cpu_rate,filesys_use_rate,memory_use_rate'
             metric_identitys='radius_percent,radius_num';
			 addSuffix='false';
			 suffix=ok;
             uploadOk=false;
        }
        JAVA_HOME='/home/omc/jdk8/jdk1.8.0_181';
        log.home='/home/omc/omc-alarm-3.0/logs';
        sendReport=true;
        province='gscm';
    }

    gscmsb{
        prefix='/home/omc/omc-alarm-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.8.103:3306/gsomc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8';
            username='gsomc';
            password='GSomc@0105';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
        smtp{

        }
        upload{
            serverIp='192.168.6.44';
            serverPort='21';
            protocol='ftp';
            loginName='KXshuju';
            password='KX22019QAZx';
            localDir='/home/omc/ftpdatas/kd_band';
            uploadDir='/home/KXshuju/host';
            metric_identitys='read_wrtn_speed,cpu_use_rate,filesys_use_rate,memory_use_rate';
			addSuffix='false'
        }
        JAVA_HOME='/home/omc/jdk8/jdk1.8.0_181';
        log.home='/home/omc/omc-alarm-3.0/logs';
        sendReport=true;
        province='gscmsb';
    }

    jscm{
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@172.133.79.79:7311:lcimsomc';
            username='omcadmin';
            password='omcAadmin32';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
			name='oracle';
        }
      sh{
            LANG='zh_CN.UTF-8';
            target='omc-alarm';
        }
        upload{
             serverIp='172.133.79.56';
             serverPort='21';
             protocol='ftp';
             loginName='netftp';
             password='netftp123';
             localDir='/lcims/omc/upload';
             uploadDir='/lcims/netftp/D_HOST_MON';
             metric_identitys='memory_use_rate,cpu_use_rate,disk_busy_rate';
        }
        prefix='/lcims/omc/omc-alarm';
        JAVA_HOME='/lcims/omc/jdk8';
        log.home='/lcims/omc/omc-alarm/logs'
        sendReport='true'
        province='jscm';
   }
    
    ahct{
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@202.102.192.119:1721:BILL70';
            username='billadmin70';
            password='billadmin';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
			name='oracle';
        }
        sh{
            LANG='zh_CN.UTF-8';
            target='omc-alarm';
        }
        prefix='/lcims/omc/omc-alarm';
		JAVA_HOME='/lcims/omc/jdk8';
        log.home='/lcims/omc/omc-alarm/logs';
		sendReport='true';
		province='ahct';
    }
	 jlcm{
		prefix='/data/omc/omc-alarm-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://172.168.19.159:3306/jlomc?useUnicode=true&characterEncoding=utf-8';
            username='root';
            password='831015';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
		smtp{
            
        }
        JAVA_HOME='/data/omc/jdk1.8.0_181';
        log.home='/data/omc/omc-alarm-3.0/logs';
        sendReport=false;
        province=jlcm;
    }
	bjcu{
		prefix='/omc/omc-alarm-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://132.77.208.8:3306/omc?useSSL=false&serverTimezone=Asia/Shanghai';
            username='omc';
            password='@014CjKl';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
		smtp{
            
        }
        JAVA_HOME='/data1/omc/jdk1.8';
        log.home='/data1/omc/omc-alarm-3.0/logs';
        sendReport=true;
		smsshellpath='/data1/omc/omc-alarm-3.0/sh/bjcu';
        province=bjcu;
    }
	hncmtest{
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.96.207.164:1521:IPCS';
            username='nomc';
            password='as1a1nf0';
            initSize='10';
            maxActive='50';
            name='oracle';
        }
		smtp{
		   
		}
		  sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
        prefix='/home/omc/omc-alarm-3.0';
		JAVA_HOME='/home/omc/jdk8';
        log.home='/home/omc/omc-alarm-3.0/logs'
		sendReport='true'
		province='hncm';
      
   }
   hncm{
       db{
           driver='oracle.jdbc.OracleDriver';
           url='jdbc:oracle:thin:@10.218.224.188:1521:OBSDB';
           username='nomc';
           password='SML12-omc';
           initSize='10';
           maxActive='50';
           name='oracle';
       }
       dbOut{
           driver='com.mysql.jdbc.Driver';
           url='jdbc:mysql://10.96.207.164:3306/cidmdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8';
		   username='root';
           password='as1a1nf0';
           initSize='10';
           maxActive='50';
           name='mysql';
       }
       upload{
           serverIp='10.218.217.42';
           serverPort='22';
           protocol='sftp';
           loginName='omc';
           password='as1a1nf0';
           localDir='/home/omc/upload';
           uploadDir='/home/omc/oltfile';
           metric_identitys='aggregate_olt';
       }
       smtp{

       }
       sh{
           LANG='zh_CN.utf8';
           target='omc_alarm';
       }
       prefix='/home/omc/omc_new/omc-alarm';
       JAVA_HOME='/home/omc/jdk8';
       log.home='/home/omc/omc_new/omc-alarm/logs'
       sendReport='true'
       province='hncm';
       out_db_exist=true
   }
   	sxcm{
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.136.220.31:1521:LCIMS70DB';
            username='omcadmin';
            password='omcadmin70sn';
            initSize='10';
            maxActive='50';
            name='oracle';
        }
		smtp{
		   
		}
		  sh{
            LANG='zh_CN.UTF-8';
            target='omc-alarm';
        }
        prefix='/data/lcims/omc/omc-alarm';
		JAVA_HOME='/data/lcims/omc/jdk8';
        log.home='/data/lcims/omc/omc-alarm/logs'
		sendReport='true'
		province='sxcm';
      
   }
   gdcu-test{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://132.100.175.35:5200/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb@123';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/data3/aiomc/omc3.0/jdk8';
        log.home='/data3/aiomc/omc3.0/omc-alarm-3.0/logs';
        sendReport=true;
        province=gdcu;
    }
	gdcu{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://132.98.3.200:2324/gdomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='OMCweb@123';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
		upload{
             serverIp='132.100.175.7';
             serverPort='9222';
             protocol='sftp';
             loginName='yaxin';
             password='r30eK5Xw';
             localDir='/data/aiomc/omc3.0/uploadfile';
             uploadDir='/Log';
             metric_identitys='';
			 addSuffix=true
			 suffix='ok'
        }
        JAVA_HOME='/data/aiomc/jdk8';
        log.home='/data/aiomc/omc3.0/omc-alarm/logs';
        sendReport=true;
        province='gdcu';
        sms_username='radius';
        sms_password='d1106ccca74e98877ed6d7890c70bb2c';
    }
	shcu{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://134.77.104.40:3306/shomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Shobs_156';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/home/omc/jdk8';
		log.home='/home/omc/omc-alarm/logs';
        sendReport=true;
		smtp{
		    host='58.247.119.48';
		    username='shs-dmc@chinaunicom.cn';
		    password='Hr@201905';
		}
        province='shcu';
    }
	jscu{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.25.80.135:3306/jscuomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='jscuomc';
            password='JSCUomc@123';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/lcims/omc/jdk8';
		log.home='/lcims/omc/omc-alarm/logs';
        sendReport=true;
		smsshellpath='/lcims/omc/omc-alarm/sh/jscu';
        province='jscu';
        alarm_min_num=1;
    }
	hncu{
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://192.169.0.10:23306/OMC?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcdev';
            password='DevCom109@';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/home/lciptv/app/jdk8';
		log.home='/home/lciptv/omc/omc-alarm/logs';
        sendReport=true;
		smsshellpath='/home/lciptv/omc/omc-alarm/sh/jscu';
        sms_ip='192.169.0.10'
        sms_port='7123'
        province='hncu';
		smtp{
		    host='smtp.qq.com';
		    username='1779324183@qq.com';
		    password='tegaqwzpkxfpbjcc';
		}
        alarm_min_num=1;
    }
	qhcm{
        db{
           driver='oracle.jdbc.OracleDriver';
		   url='jdbc:oracle:thin:@10.237.166.104:1521:cdsn80';
           username='QHOMC_JK';
           password='Qhyd^#104';
           initSize='10';
           maxActive='50';
           name='oracle';
        }
        JAVA_HOME='/lcims/omc/jdk8';
		prefix='/lcims/omc/omc-alarm'
		log.home='/lcims/omc/omc-alarm/logs';
        sendReport=true;
        province='qhcm';
		alarm_min_num=0;
    }
	shcm{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.9.234.46:3306/OMC?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='OMC@wlan';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/home/OMC/jdk8';
		log.home='/home/OMC/omc-alarm/logs';
        province='shcm';
        sendReport=true;
    }
    jscmom{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://172.133.79.150:3306/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Asia0mc%123';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/usr';
		log.home='/lcims/omc/omc-alarm/logs';
        province='jscmom';
        sendReport='flase';
    }
	ahcm{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.147.202.106:3306/ahomc?useUnicode=true&amp;characterEncoding=utf-810.147.202.106ahomc';
            username='ahomc';
            password='AHCM#admin123';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/lcims/omc/jdk8';
		log.home='/lcims/omc/omc-alarm/logs';
        province='ahcm';
        sendReport='true';
		smsshellpath='/lcims/smsmon';
		sms_ip='10.147.202.79'
        sms_port='9922'
		alarm_min_num=1;
		}
		ai5g{
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://10.1.198.199:3306/omc?useSSL=false&serverTimezone=Hongkong';
            username='omc';
            password='omc%0907!';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
		smtp{
            host='';
            username='';
            password='';
        }
		sms_username='';
        sms_password='';
        JAVA_HOME='/home/ai5g/local/jdk8';
		log.home='/home/ai5g/omc/omc-alarm/logs';
        province='ai5g';
        sendReport='true'
		}
		zywlw{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.81.53:23306/omcdb?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcuser';
            password='7r@4S*9pEg';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/usr';
		log.home='/aiiot/omc/omc-alarm/logs';
        province='zywlw';
        sendReport='true';
		pushdata_loginurl="http://192.168.184.220:8080/operations/pushdata/pushdataLogin/login";// 登录地址
        pushdata_username="radius-east";// 用户名
        pushdata_password="2DKzDA5ivYMgndMy";// 密码
        pushdata_pushurl="http://192.168.184.220:8080/operations/pushdata/pushdataController/pushAlarmData";// 推送地址
    }
	gzcm{
	        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@192.50.50.115:1521:aaa';
            username='aaa2omc';
            password='AaA#MaNag1Omc';
            initSize='10';
            maxActive='50';
            name='oracle';
        }
		  sh{
            LANG='zh_CN.UTF-8';
            target='omc-alarm';
        }
		smtp{
		    host='';
		    username='xxxchinaunicom.cn';
		    password='xxx';
		}
        prefix='/data/AIAAA/omc/omc-alarm';
		JAVA_HOME='/data/AIAAA/omc/jdk8';
        log.home='/data/AIAAA/omc/omc-alarm/logs'
		sendReport='true'
		province='gzcm';
        sms_username='xxx';
        sms_password='xxxx';
   }
   	gscu{
		prefix='/home/omc/omc-alarm'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.1.1.18:3306/gsomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='gsomc';
            password='GSomc@0105';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        sh{
            LANG='zh_CN.utf8';
            target='omc_alarm';
        }
        JAVA_HOME='/home/omc/jdk8/jdk1.8.0_181';
        log.home='/home/omc/omc-alarm/logs';
        sendReport=true;
        province='gscu';
    }
	zywlwtest{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.106.119:3306/omcdb?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcuser';
            password='omcuser@123';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        JAVA_HOME='/usr';
		log.home='/iot/omc/omc-alarm/logs';
        province='zywlw';
        sendReport='true';
	    pushdata_loginurl="http://10.182.251.64:8080/operations/pushdata/pushdataLogin/login";// 登录地址
        pushdata_username="radius-east";// 用户名
        pushdata_password="abcd1234";// 密码
        pushdata_pushurl="http://10.182.251.64:8080/operations/pushdata/pushdataController/pushAlarmData";// 推送地址
    }
	
	nfvtest{
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_nmcu?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
        dbOut{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_nmcu?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            maxActive='50';
            name='mysql';
        }
		upload{
             serverIp='10.1.198.31';
             serverPort='22';
             protocol='sftp';
             loginName='ai5g';
             password='ipQA135%';
             localDir='/home/lcims/omc/zy';
             uploadDir='/home/ai5g/omc/zy';
			 uploadDirPM='/home/ai5g/omc/test';
             metric_identitys='memory_use_rate,cpu_use_rate,disk_busy_rate';
             resourceFileNamePrefix='GD-CM-PTN-SCTPASSOC-A001-V1.1.0-';
             performFileNamePrefix='GD-PM-PTN-SCTPASSOC-B001-V1.1.0-';
             vendorName='asiainfo';
             elementType='PTN';
             cmVersion='V1.0.0';
             pmVersion='V1.0.0';
             objectType='OMC';
             rmUID='1301FHCS1';
        }
        JAVA_HOME='/home/lcims/app/jdk8';
        log.home='/home/lcims/omc/omc-alarm-3.0/logs';
        sendReport=true;
        province='nfv';
    }
	
}