prefix='/home/lcims/dev/build/omc-web'
province='develop'
provincename='北京'
timedTask='false'
homepage='/view/monitor/app'
systemname='WLAN监控管理系统'
port=9002
httpsflag='false'
db{
    driver='com.mysql.jdbc.Driver';
}
sh{
    LANG='zh_CN.utf8'
    target='omcweb'
}
forgetflag='false'
environments {
    dev{
            prefix='/home/lcims/omc/omc-web-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_nmcu?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9004
        JAVA_HOME='/home/lcims/app/jdk8'
        log.home='/home/lcims/omc/omc-web-3.0/logs'
        province='develop'
        provincename='develop'
        homepage='/view/class/home'
        systemname='宽带接入运维平台'
		forgetflag=true 
    }
    autodeploy{
            prefix='/home/lcims/omcautodeploy/omc-web-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_test?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        autodeploySwitch='true'
        timedTask='true'
        httpsflag='false'
        port=9904
        JAVA_HOME='/home/lcims/app/jdk8'
        log.home='/home/lcims/omcautodeploy/omc-web-3.0/logs'
        province='autodeploy'
        provincename='autodeploy'
        homepage='/view/class/server/module'
        systemname='宽带接入运维平台'
    }
    demo{
            prefix='/home/lcims/omcdemo/omc-web-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_demo?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9104
        JAVA_HOME='/home/lcims/app/jdk8'
        log.home='/home/lcims/omcdemo/omc-web-3.0/logs'
        province='demo'
        provincename='demo'
        homepage='/view/class/home'
        systemname='宽带接入运维平台演示系统'
    }
    develop{
            prefix='/home/lcims/omc/omc-web-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_nmcu?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9004
        JAVA_HOME='/home/lcims/app/jdk8'
        log.home='/home/lcims/omc/omc-web-3.0/logs'
        province='develop'
        provincename='develop'
        homepage='/view/class/home'
        systemname='宽带接入运维平台'
    }
	
    nmcu{
            prefix='/export/home/omc/omc-web-3.0'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@110.19.17.31:1521:aiomc';
            username='omc';
            password='omc_nmlt';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        JAVA_HOME='/export/home/omc/app/jdk1.8.0_181'
        log.home='/export/home/omc/omc-web-3.0/logs'
        province='nmcu'
        provincename='内蒙'
        homepage='/view/class/server/module'
        systemname='内蒙联通宽带接入可视化运维平台'
        port=9004

    }
	
	sicu{
           prefix='/home/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@218.26.146.13:1521:ORA11G';
            username='aimnt';
            password='Aisicuomc123#';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'  
        JAVA_HOME='/home/omc/jdk8'
        log.home='/home/omc/omc-web/logs'
        province='sicu'
        provincename='山西'
        homepage='/view/class/home'
        systemname='山西联通宽带接入可视化运维平台'
        port=9002
    }
	
	xjcu{
            prefix='/home/omc/omc-web-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://10.7.15.38:3306/omc_xjcu?useSSL=false&amp;serverTimezone=Asia/Shanghai&amp;useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Omc@1234';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1';
        }
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/home/omc/app/jdk1.8'
        log.home='/home/omc/omc-web-3.0/logs'
        province='xjcu'
        provincename='新疆'
        homepage='/view/class/server/module'
        systemname='新疆联通宽带接入可视化运维平台'
        port=9004

    }
	nmct{
            prefix='/omc/omc-web-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://192.168.100.80:3306/omc?useSSL=false&amp;allowPublicKeyRetrieval=true&amp;serverTimezone=Asia/Shanghai&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true';
            username='omc';
            password='nmobs%3A';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1';
        }
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/home/jdk1.8.0_181'
        log.home='/omc/omc-web-3.0/logs'
        province='nmct'
        provincename='内蒙'
        homepage='/view/class/home'
        systemname='内蒙电信宽带接入可视化运维平台'
        port=9002

    }
	gscm{
            prefix='/home/omc/omc-web-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.8.103:3306/gsomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='gsomc';
            password='GSomc@0105';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/home/omc/jdk8/jdk1.8.0_181'
        log.home='/home/omc/omc-web-3.0/logs'
        province='gscm'
        provincename='甘肃'
        homepage='/view/class/home'
        systemname='甘肃移动宽带接入可视化运维平台'
        port=9002

    }
	jscm{
           prefix='/lcims/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver';
			url='jdbc:oracle:thin:@172.133.79.79:7311:lcimsomc';
            username='omcadmin';
            password='omcAadmin32';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
        JAVA_HOME='/lcims/omc/jdk1.8.0_181'
        log.home='/lcims/omc/omc-web/logs'
        province='jscm'
        provincename='江苏'
        homepage='/view/class/home'
        systemname='江苏移动宽带接入可视化运维平台'
        port=9002
		forgetflag='true'
    }
	jscmtest{
           prefix='/lcims/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@172.133.79.40:1521:lcimstest';
            username='omcadmin';
            password='omcAadmin32';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
        JAVA_HOME='/lcims/omc/jdk8'
        log.home='/lcims/omc/omc-web/logs'
        province='jscm'
        provincename='江苏'
        homepage='/view/class/system'
        systemname='11'
        port=9102
        forgetflag='true'
    }
	
	ahct{
           prefix='/lcims/lcims70/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.110.10.5:1521:BILL70';
            username='billadmin70';
            password='billadmin';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
        JAVA_HOME='/lcims/lcims70/omc/jdk8'
        log.home='/lcims/lcims70/omc/omc-web/logs'
        province='ahct'
        provincename='安徽'
        homepage='/view/class/home'
        systemname='安徽电信宽带接入可视化运维平台'
        port=9002
    }
    
    ahct_test{
           prefix='/lcims/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.110.10.5:1521:BILL70';
            username='omcuser';
            password='omcyx#2020';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
        JAVA_HOME='/lcims/omc/jdk8'
        log.home='/lcims/omc/omc-web/logs'
        province='ahct'
        provincename='安徽'
        homepage='/view/class/home'
        systemname='安徽电信宽带接入可视化运维平台'
        port=9002
    }
    
	jlcm{
            prefix='/data/omc/omc-web-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://172.168.19.159:3306/jlomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='root';
            password='831015';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/data/omc/jdk1.8.0_181'
        log.home='/data/omc/omc-web-3.0/logs'
        province='jlcm'
        provincename='吉林'
        homepage='/view/class/server/module'
        systemname='吉林移动宽带接入可视化运维平台'
        port=9002

    }
    bjcu{
            prefix='/omc/omc-web-3.0'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://132.77.208.8:3306/omc?useSSL=false&amp;serverTimezone=Asia/Shanghai&amp;autoReconnect=true';
            username='omc';
            password='@014CjKl';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/data1/omc/jdk1.8'
        log.home='/data1/omc/omc-web-3.0/logs'
        province='bjcu'
        provincename='北京'
        homepage='/view/class/server/module'
        systemname='北京联通宽带接入可视化运维平台'
        port=9002

    }
	hncmtest{
           prefix='/home/omc/omc-web-3.0'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.96.207.164:1521:IPCS';
            username='nomc';
            password='as1a1nf0';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
        JAVA_HOME='/home/omc/jdk8'
        log.home='/home/omc/omc-web-3.0/logs'
        province='hncm'
        provincename='河南'
        homepage='/view/class/city/module'
        systemname='河南移动宽带接入可视化运维平台'
        port=8007
    }
	hncm{
           prefix='/home/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver'
            url='jdbc:oracle:thin:@10.218.224.188:1521:OBSDB';
            username='nomc';
            password='SML12-omc';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
        JAVA_HOME='/home/omc/omc_new/omc/jdk8'
        log.home='/home/omc/omc_new/omc-web/logs'
        province='hncm'
        provincename='河南'
        homepage='/view/class/city/module'
        systemname='河南移动宽带接入可视化运维平台'
        port=8007
		forgetflag='false'
    }
	sxcm{
           prefix='/data/lcims/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.136.220.31:1521:LCIMS70DB';
            username='omcadmin';
            password='omcadmin70sn';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/data/lcims/omc/jdk8'
        log.home='/data/lcims/omc/omc-web/logs'
        province='sxcm'
        provincename='陕西'
        homepage='/view/class/home'
        systemname='陕西移动宽带接入可视化运维平台'
        port=9112
    }
    gdcu20{
            prefix='/data3/aiomc/omc3.0/omc-web-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://132.100.175.35:5200/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb@123';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        hbase{
            zookeeperQuorum='hz-accesslog1:2181,hz-accesslog2:2181,hz-accesslog3:2181'
        }
        timedTask='true'
        httpsflag='true'
        port=9992
        JAVA_HOME='/data3/aiomc/omc3.0/jdk8'
        log.home='/data3/aiomc/omc3.0/omc-web-3.0/logs'
        province='gdcu'
        provincename='gdcu'
        homepage='/view/class/system'
        systemname='广东联通宽带接入运维平台'
    }
	gdcu{
            prefix='/data/aiomc/omc3.0/omc-web'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://132.98.3.200:2324/gdomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='OMCweb@123';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        hbase{
            zookeeperQuorum='hz-accesslog1:2181,hz-accesslog2:2181,hz-accesslog3:2181'
        }
        timedTask='true'
        httpsflag='true'
        port=2325
        JAVA_HOME='/data/aiomc/jdk8'
        log.home='/data/aiomc/omc3.0/omc-web/logs'
        province='gdcu'
        provincename='gdcu'
        homepage='/view/class/home'
        systemname='广东联通宽带接入运维平台'

    }
	 gdcubak{
            prefix='/data3/aiomc/omc3.0/omc-web-3.0-bak'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://132.96.231.20:11500/gdomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='GdOmc@0924';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
         hbase{
             zookeeperQuorum='hz-accesslog1:2181,hz-accesslog2:2181,hz-accesslog3:2181'
         }
        timedTask='true'
        httpsflag='true'
        port=2325
        JAVA_HOME='/data3/aiomc/omc3.0/jdk8'
        log.home='/data3/aiomc/omc3.0/omc-web-3.0-bak/logs'
        province='gdcu'
        provincename='gdcu'
        homepage='/view/class/system'
        systemname='广东联通宽带接入运维平台'
    }
	shcu{
	  prefix='/home/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://134.77.104.40:3306/shomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Shobs_156';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        autodeploySwitch='false'
        timedTask='true'
        httpsflag='false'
        port=9002
        JAVA_HOME='/home/omc/jdk8'
        log.home='/home/omc/omc-web/logs'
        province='shcu'
        provincename='shcu'
        homepage='/view/class/home'
        systemname='上海联通宽带接入运维平台'
	}
	jscu{
	  prefix='/lcims/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.25.80.135:3306/jscuomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='jscuomc';
            password='JSCUomc@123';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9002
        JAVA_HOME='/lcims/omc/jdk8'
        log.home='/lcims/omc/omc-web/logs'
        province='jscu'
        provincename='jscu'
        homepage='/view/class/system'
        systemname='江苏联通宽带接入运维平台'
	}
	byomc{
	  prefix='/lcims/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.1.198.92:3306/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Omc20190724%';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9002
        JAVA_HOME='/home/lcims/omc/jdk8'
        log.home='/home/lcims/omc/omc-web/logs'
        province='byomc'
        provincename='byomc'
        homepage='/view/class/system'
        systemname='创新部宽带接入运维平台'
	}
	hncu{
           prefix='/home/lciptv/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://192.169.0.10:23306/OMC?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcdev';
            password='DevCom109@';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
		timedTask='true'
        JAVA_HOME='/home/lciptv/app/jdk8'
        log.home='/home/lciptv/omc/omc-web/logs'
        province='hncu'
		httpsflag='true'
        provincename='河南'
        homepage='/view/class/system'
        systemname='河南联通IPTV管理平台'
        port=18001
    }
	qhcm{
           prefix='/lcims/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.237.166.104:1521:cdsn80';
            username='QHOMC_JK';
            password='Qhyd^#104';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/lcims/omc/jdk8'
        log.home='/lcims/omc/omc-web/logs'
        province='qhcm'
        provincename='青海'
        homepage='/view/class/system'
        systemname='青海移动宽带接入可视化运维平台'
        port=9051
    }
	shcm{
           prefix='/home/OMC/omc-web'
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://10.9.234.46:3306/OMC?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='OMC@wlan';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1';
        }  
        JAVA_HOME='/home/OMC/jdk8'
        log.home='/home/OMC/omc-web/logs'
        province='shcm'
        provincename='上海'
        homepage='/view/class/system'
        systemname='上海移动宽带接入可视化运维平台'
        port=9002
    }
	jscmom{
           prefix='/lcims/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://172.133.79.150:3306/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Asia0mc%123';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1';
        }  
        JAVA_HOME='/usr'
        log.home='/lcims/omc/omc-web/logs'
        province='jscmom'
        provincename='江苏大数据中心'
        homepage='/view/class/system'
        systemname='江苏移动大数据中心可视化运维平台'
        port=9002
    }
	ems{
           prefix='/home/nfv/software/wanghl/omc'
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://172.133.79.150:3306/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Asia0mc%123';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1';
        }  
        JAVA_HOME='/usr/local/jdk/jdk1.8.0_91'
        log.home='/home/nfv/software/wanghl/omc/omc-web/logs'
        province='ems'
        provincename='NFVAAA'
        homepage='/view/class/system'
        systemname='NFVAAA可视化运维平台'
        port=9002
    }
	ahcm{
            prefix='/lcims/omc/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.147.202.106:3306/ahomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='ahomc';
            password='AHCM#admin123';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9004
        JAVA_HOME='/lcims/omc/jdk8'
        log.home='/lcims/omc/omc-web/logs'
        province='ahcm'
        provincename='ahcm'
        homepage='/view/class/server/module/device/node/summary'
        systemname='安徽移动宽带接入运维平台'
		forgetflag=false 
    }
	gscm5G{
            prefix='/home/ai5g/omc/omc-web'
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://10.1.198.199:3306/omc?useSSL=false&amp;allowPublicKeyRetrieval=true&amp;serverTimezone=Asia/Shanghai&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true';
            username='omc';
            password='omc%0907!';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9014
        JAVA_HOME='/home/ai5g/local/jdk8'
        log.home='/home/ai5g/omc/omc-web-3.0/logs'
        province='gscm5G'
        provincename='gscm5G'
        homepage='/view/class/home'
        systemname='5G防火墙日志采集平台'
		forgetflag=true
    }
	cqcm{
            prefix='/aiiot/omc/omc-web-3.0'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.81.53:23306/omcdb?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcuser';
            password='7r@4S*9pEg';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9002
        JAVA_HOME='/usr'
        log.home='/aiiot/omc/omc-web-3.0/logs'
        province='cqcm'
        provincename='cqcm'
        homepage='/view/class/system'
        systemname='中移物联网管理系统'
		forgetflag=false 
		autodeploySwitch='true'
    }
	gzcm{
           prefix='/data/AIAAA/omc/omc-web'
        db{
            driver='oracle.jdbc.OracleDriver'
            url='jdbc:oracle:thin:@192.50.50.115:1521:aaa';
            username='aaa2omc';
            password='AaA#MaNag1Omc';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }  
        JAVA_HOME='/home/aiomc/omc/jdk1.8'
        log.home='/home/aiomc/omc/omc-web/logs'
        province='gzcm'
        provincename='gzcm'
        homepage='/view/class/system'
        systemname='贵州移动宽带接入可视化运维平台'
        port=62302
		forgetflag='false'
    }
	gscu{
            prefix='/home/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.1.1.18:3306/gsomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='gsomc';
            password='GSomc@0105';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
		timedTask='true'
        httpsflag='false'
        JAVA_HOME='/home/omc/jdk8/'
        log.home='/home/omc/omc-web/logs'
        province='gscu'
        provincename='甘肃'
        homepage='/view/class/home'
        systemname='甘肃联通宽带接入可视化运维平台'
        port=9002

    }
	cqcmtest{
            prefix='/iot/omc/omc-web'
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.106.119:3306/omcdb?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcuser';
            password='omcuser@123';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        timedTask='true'
        httpsflag='false'
        port=9002
        JAVA_HOME='/usr'
        log.home='/iot/omc/omc-web/logs'
        province='cqcmtest'
        provincename='cqcmtest'
        homepage='/view/class/system'
        systemname='中移物联网管理系统'
		forgetflag=false 
		autodeploySwitch='true'
    }
	
}
