
package com.asiainfo.lcims.omc.alarm.sms.gdcu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsForwardService", targetNamespace = "http://alarmforward.zznode.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsForwardService {


    /**
     * 
     * @param sendSmsReq
     * @return
     *     returns com.asiainfo.lcims.omc20.alarm.sms.gdcu.SendSmsRsp
     */
    @WebMethod
    @WebResult(name = "sendSmsRsp", targetNamespace = "http://alarmforward.zznode.com", partName = "sendSmsRsp")
    public SendSmsRsp sendSms(
        @WebParam(name = "sendSmsReq", targetNamespace = "http://alarmforward.zznode.com", partName = "sendSmsReq")
        SendSmsReq sendSmsReq);

}
