
package com.asiainfo.lcims.omc.alarm.sms.gdcu;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmsForwardService", targetNamespace = "http://alarmforward.zznode.com", wsdlLocation = "http://132.96.68.31:3382/alarmViewFlat/services/sendSms?wsdl")
public class SmsForwardService_Service
    extends Service
{

    private final static URL SMSFORWARDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSFORWARDSERVICE_EXCEPTION;
    private final static QName SMSFORWARDSERVICE_QNAME = new QName("http://alarmforward.zznode.com", "SmsForwardService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://132.96.68.31:3382/alarmViewFlat/services/sendSms?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSFORWARDSERVICE_WSDL_LOCATION = url;
        SMSFORWARDSERVICE_EXCEPTION = e;
    }

    public SmsForwardService_Service() {
        super(__getWsdlLocation(), SMSFORWARDSERVICE_QNAME);
    }

    public SmsForwardService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSFORWARDSERVICE_QNAME, features);
    }

    public SmsForwardService_Service(URL wsdlLocation) {
        super(wsdlLocation, SMSFORWARDSERVICE_QNAME);
    }

    public SmsForwardService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSFORWARDSERVICE_QNAME, features);
    }

    public SmsForwardService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsForwardService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmsForwardService
     */
    @WebEndpoint(name = "sendSms")
    public SmsForwardService getSendSms() {
        return super.getPort(new QName("http://alarmforward.zznode.com", "sendSms"), SmsForwardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmsForwardService
     */
    @WebEndpoint(name = "sendSms")
    public SmsForwardService getSendSms(WebServiceFeature... features) {
        return super.getPort(new QName("http://alarmforward.zznode.com", "sendSms"), SmsForwardService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSFORWARDSERVICE_EXCEPTION!= null) {
            throw SMSFORWARDSERVICE_EXCEPTION;
        }
        return SMSFORWARDSERVICE_WSDL_LOCATION;
    }

}
