collectClientTarget="omc_collect_client"
collectServerTarget="omc_collect_server"
delimiter="\$\$\$"
reconnect_time=10
heart_time=20

environments {
    dev{
        server{
            ip="10.21.37.197";
            port="9999";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_nmcu?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/lcims/omc/collectserver'
        client_work_home='/home/lcims/omc/collectclient'
        JAVA_HOME='/home/lcims/app/jdk8'
    }
    autodeploy{
        server{
            ip="10.21.37.197";
            port="9209";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_test?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/lcims/omcautodeploy/collectserver'
        client_work_home='/home/lcims/omcautodeploy/collectclient'
        JAVA_HOME='/home/lcims/app/jdk8'
    }
	demo{
        server{
            ip="10.21.37.197";
            port="9109";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_demo?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/lcims/omcdemo/collectserver'
        client_work_home='/home/lcims/omcdemo/collectclient'
        JAVA_HOME='/home/lcims/app/jdk8'
    }
	nmcu{
        server{
            ip="110.19.16.116";
            port="9999";
        }
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@110.19.17.31:1521:aiomc';
            username='omc';
            password='omc_nmlt';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/export/home/omc/collectserver'
        client_work_home='/export/home/omc/collectclient'
        JAVA_HOME='/export/home/omc/app/jdk1.8.0_181'
    }
	
	sicu{
        server{
            ip="218.26.146.13";
            port="9003";
        }
        db{
            driver='oracle.jdbc.driver.OracleDriver';
            url='jdbc:oracle:thin:@218.26.146.13:1521:ORA11G';
            username='aimnt';
            password='Aisicuomc123#';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/omc/collectserver'
        client_work_home='/home/omc/collectclient'
        JAVA_HOME='/home/omc/jdk8'
    }

	xjcu{
        server{
            ip="10.7.15.38";
            port="9999";
        }
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://10.7.15.38:3306/omc_xjcu?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8';
            username='omc';
            password='Omc@1234';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/omc/collectserver'
        client_work_home='/home/omc/collectclient'
        JAVA_HOME='/home/omc/app/jdk1.8'
    }
	nmct{
        server{
            ip="192.168.100.80";
            port="9003";
        }
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://192.168.100.80:3306/omc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8';
            username='omc';
            password='nmobs%3A';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/omc/collectserver'
        client_work_home='/omc/collectclient'
        JAVA_HOME='/home/jdk1.8.0_181'
    }
	gscm{
        server{
            ip="192.168.8.103";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.8.103:3306/gsomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='gsomc';
            password='GSomc@0105';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/omc/collectserver'
        client_work_home='/home/omc/collectclient'
        JAVA_HOME='/home/omc/jdk8/jdk1.8.0_181'
    }
	jscm{
        server{
            ip="172.133.79.213";
            port="9003";
        }
        db{
            driver='oracle.jdbc.driver.OracleDriver';
            url='jdbc:oracle:thin:@172.133.79.79:7311:lcimsomc';
            username='omcadmin';
            password='omcAadmin32';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/lcims/omc/collectserver'
        client_work_home='/lcims/omc/collectclient'
        JAVA_HOME='/lcims/omc/jdk8'
    }
    
    ahct{
        server{
            ip="10.110.8.3";
            port="9003";
        }
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.110.10.5:1521:BILL70';
            username='billadmin70';
            password='billadmin';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        LANG='zh_CN.utf8'
        JAVA_HOME='/lcims/lcims70/omc/jdk8'
        server_work_home='/lcims/lcims70/omc/collectserver'
        client_work_home='/lcims/lcims70/omc/collectclient'
    }
    
    ahct_test{
        server{
            ip="10.110.8.3";
            port="9003";
        }
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@202.102.192.119:1721:BILL70';
            username='omcuser';
            password='omcyx#2020';
            initSize='10';
            minIdle='10';
            maxActive='50';
            testSql='select 1 from dual';
        }
        LANG='zh_CN.utf8'
        JAVA_HOME='/lcims/omc/jdk8'
        server_work_home='/lcims/omc/collectserver'
        client_work_home='/lcims/omc/collectclient'
    }
    
	jlcm{
        server{
            ip="172.168.19.159";
            port="9003";
        }
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://172.168.19.159:3306/jlomc?useUnicode=true&characterEncoding=utf-8';
            username='root';
            password='831015';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/data/omc/collectserver'
        client_work_home='/data/omc/collectclient'
        JAVA_HOME='/data/omc/jdk1.8.0_181'
    }
	jlcm1{
	    server{
            ip="111.26.29.84";
            port="9003";
        }
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://111.26.29.84:3306/jlomc?useUnicode=true&characterEncoding=utf-8';
            username='root';
            password='831015';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/data/omc/collectserver'
        client_work_home='/data/omc/collectclient'
        JAVA_HOME='/data/omc/jdk1.8.0_181'
    }
    bjcu{
        server{
            ip="132.77.208.8";
            port="9003";
        }
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://132.77.208.8:3306/omc?useSSL=false&serverTimezone=Hongkong';
            username='omc';
            password='@014CjKl';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/data1/omc/collectserver'
        client_work_home='/data1/omc/collectclient'
        JAVA_HOME='/data1/omc/jdk1.8'
    }
	hncmtest{
        server{
            ip="10.96.207.61";
            port="9004";
        }
        db{
            driver='oracle.jdbc.driver.OracleDriver'
            url='jdbc:oracle:thin:@10.96.207.164:1521:IPCS';
            username='nomc';
            password='as1a1nf0';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/omc/collectserver'
        client_work_home='/home/radius/omc/collectclient'
        JAVA_HOME='/home/omc/jdk8'
    }
	hncm{
        server{
            ip="10.218.217.42";
            port="9070";
        }
        db{
            driver='oracle.jdbc.driver.OracleDriver'
            url='jdbc:oracle:thin:@10.218.224.188:1521:OBSDB';
            username='nomc';
            password='SML12-omc';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/radius/omc/omc_new/collectserver'
        client_work_home='/home/radius/omc/omc_new/collectclient'
        JAVA_HOME='/home/radius/omc/jdk8'
    }
	sxcm{
        server{
            ip="10.136.220.82";
            port="9004";
        }
        db{
            driver='oracle.jdbc.driver.OracleDriver';
            url='jdbc:oracle:thin:@10.136.220.31:1521:LCIMS70DB';
            username='omcadmin';
            password='omcadmin70sn';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/data/lcims/omc/collectserver'
        client_work_home='/data/lcims/omc/collectclient'
        JAVA_HOME='/data/lcims/omc/jdk8'
    }
     gdcu-test{
        server{
            ip="132.96.231.20";
            port="9999";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://132.100.175.35:5200/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb@123';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/data3/aiomc/omc3.0/collectserver'
        client_work_home='/data3/aiomc/omc3.0/collectclient'
        JAVA_HOME='/data3/aiomc/omc3.0/jdk8'
    }
	gdcu{
        server{
            ip="132.98.3.200";
            port="2328";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://132.98.3.200:2324/gdomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='OMCweb@123';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/data/aiomc/omc3.0/collectserver'
        client_work_home='/data/aiomc/omc3.0/collectclient'
        JAVA_HOME='/data/aiomc/jdk8'
    }
	 shcu{
        server{
            ip="134.77.104.39";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://134.77.104.40:3306/shomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Shobs_156';
            initSize='10';
            maxActive='50';

        }
        LANG='zh_CN.utf8'
        server_work_home='/home/omc/collectserver'
        client_work_home='/data/omc/collectclient'
        JAVA_HOME='/data/omc/jdk8'
    }
	jscu{
        server{
            ip="10.25.80.135";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.25.80.135:3306/jscuomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='jscuomc';
            password='JSCUomc@123';
            initSize='10';
            maxActive='50';

        }
        LANG='zh_CN.utf8'
        server_work_home='/lcims/omc/collectserver'
        client_work_home='/lcims/omc/collectclient'
        JAVA_HOME='/lcims/omc/jdk8'
    }
	byomc{
        server{
            ip="10.1.198.92";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.1.198.92:3306/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Omc20190724%';
            initSize='10';
            maxActive='50';

        }
        LANG='zh_CN.utf8'
        server_work_home='/home/lcims/omc/collectserver'
        client_work_home='/home/lcims/omc/collectclient'
        JAVA_HOME='/home/lcims/omc/jdk8'
    }
	    ahct{
        server{
            ip="10.21.37.197";
            port="9997";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.21.37.197:3306/omc_ahct?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcweb';
            password='omcweb';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/lcims/ahct/collectserver'
        client_work_home='/home/lcims/ahct/collectclient'
        JAVA_HOME='/home/lcims/app/jdk8'
    }
	hncu{
        server{
            ip="192.169.0.20";
            port="18003";
        }
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://192.169.0.10:23306/OMC?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcdev';
            password='DevCom109@';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/lciptv/omc/collectserver'
        client_work_home='/home/lciptv/omc/collectclient'
        JAVA_HOME='/home/lciptv/app/jdk8'
    }
	qhcm{
        server{
            ip="10.237.166.104";
            port="9053";
        }
        db{
            driver='oracle.jdbc.OracleDriver';
            url='jdbc:oracle:thin:@10.237.166.104:1521:cdsndbtest';
            username='QHOMC_JK';
            password='Qhyd^#104';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/lcims/omc/collectserver'
        client_work_home='/lcims/omc/collectclient'
        JAVA_HOME='/lcims/omc/jdk8'
    }
	shcm{
        server{
            ip="10.9.234.46";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://10.9.234.46:3306/OMC?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='OMC@wlan';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/OMC/collectserver'
        client_work_home='/home/OMC/collectclient'
        JAVA_HOME='/home/OMC/jdk8'
    }
	jscmom{
        server{
            ip="172.133.79.150";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver'
            url='jdbc:mysql://172.133.79.150:3306/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Asia0mc%123';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/lcims/omc/collectserver'
        client_work_home='/lcims/omc/collectclient'
        JAVA_HOME='/usr'
    }
	ahcm{
        server{
            ip="10.147.202.106";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.147.202.106:3306/ahomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='ahomc';
            password='AHCM#admin123';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/lcims/omc/collectserver'
        client_work_home='/lcims/omc/collectclient'
        JAVA_HOME='/lcims/omc/jdk8'
    }
	ai5g{
        server{
            ip="10.1.198.31";
            port="9013";
        }
        db{
            driver='com.mysql.cj.jdbc.Driver';
            url='jdbc:mysql://10.1.198.199:3306/omc?useSSL=false&serverTimezone=Hongkong';
            username='omc';
            password='omc%0907!';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/ai5g/omc/collectserver'
        client_work_home='/home/ai5g/omc/collectclient'
        JAVA_HOME='/home/ai5g/local/jdk8'
    }
	cqcm{
        server{
            ip="192.168.81.78";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.81.53:23306/omcdb?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcuser';
            password='7r@4S*9pEg';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/aiiot/omc/collectserver'
        client_work_home='/aiiot/omc/collectclient'
        JAVA_HOME='/usr'
    }
	gzcm{
        server{
            ip="192.50.50.115";
            port="62303";
        }
        db{
            driver='oracle.jdbc.driver.OracleDriver';
            url='jdbc:oracle:thin:@192.50.50.115:1521:aaa';
            username='aaa2omc';
            password='AaA#MaNag1Omc';
            initSize='10';
            maxActive='50';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/aiomc/collectserver'
        client_work_home='/home/ai/omc/collectclient'
        JAVA_HOME='/home/aiomc/jdk1.8'
    }
	gscu{
        server{
            ip="10.1.1.18";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.1.1.18:3306/gsomc?useUnicode=true&amp;characterEncoding=utf-8';
            username='gsomc';
            password='GSomc@0105';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/omc/collectserver'
        client_work_home='/home/omc/collectclient'
        JAVA_HOME='/home/omc/jdk8/jdk1.8.0_181'
    }
	cqcmtest{
        server{
            ip="192.168.106.120";
            port="9003";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://192.168.106.119:3306/omcdb?useUnicode=true&amp;characterEncoding=utf-8';
            username='omcuser';
            password='omcuser@123';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/iot/omc/collectserver'
        client_work_home='/iot/omc/collectclient'
        JAVA_HOME='/usr'
    }
	shomc{
        server{
            ip="10.222.56.10";
            port="8303";
        }
        db{
            driver='com.mysql.jdbc.Driver';
            url='jdbc:mysql://10.222.56.10:3306/omc?useUnicode=true&amp;characterEncoding=utf-8';
            username='omc';
            password='Wlan@1357';
            initSize='5';
            maxActive='10';
        }
        LANG='zh_CN.utf8'
        server_work_home='/home/hadoop/omc/collectserver'
        client_work_home='/home/hadoop/omc/collectclient'
        JAVA_HOME='/'
    }
}
